[module/xworkspaces]
type = internal/xworkspaces

reverse-scroll = true

label-active = 
label-active-foreground = ${colors.base05}
#label-active-background = ${colors.base01}
#label-active-underline = ${colors.base05}
label-active-padding = 2

label-occupied = 
label-occupied-foreground = ${colors.base03}
label-occupied-padding = 2

label-urgent = 
label-urgent-foreground = ${colors.base08}
label-urgent-padding = 2

label-empty = 
label-empty-foreground = ${colors.base03}
label-empty-padding = 2

[module/date]
type = internal/date

interval = 1

date = "%a %b %d "
date-alt = ""

time = %T
time-alt = %T

label = %date%%time%
label-foreground = ${colors.base05}

