#!/bin/sh

$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d sh ed www mp etc

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_motion_interval 7ms

bspc config focused_border_color "#A0A0A0"
bspc config normal_border_color "#111111"
bspc config presel_feedback_color "#111111"

bspc rule -a kitty state=pseudo_tiled
bspc rule -a Code desktop='^2' follow=on
bspc rule -a jetbrains-goland desktop='^2' follow=on
bspc rule -a jetbrains-webstorm desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Cider desktop='^4'
bspc rule -a Slack desktop='^5'
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a openrgb state=pseudo_tiled
