#! /bin/sh

$HOME/.fehbg &
$HOME/.config/polybar/launch.sh &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term code web music etc

bspc config focus_follows_pointer	true
bspc config ignore_ewmh_focus		true

bspc config border_width		0
bspc config window_gap			12

bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true

bspc rule -a Code desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Cider desktop='^4'
bspc rule -a Slack desktop='^5' state=pseudo_tiled

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
