# Explanation and default values for keys:

# # Through which shell command hooks will run. The command will be replaced in '{}'
# shell = "sh -c '{}'"
#
# [[items]]
# # File to inject to, supports tilde and env var expansion. required
# file = "~/.config/example"
# # Template to use. required
# template = "example"
# # Subtemplate to use
# subtemplate = "default"
# # If not rewriting, on which line (usually a comment) to start replacing
# start = "# Start flavours"
# # If not rewriting, on which line (usually a comment) to stop replacing
# end = "# End flavours"
# # Should we rewrite the entire file, instead of using the above delimiters?
# rewrite = false
# # Command to execute after injecting (goes through shell)
# hook = ""
# # Whether this hook should be executed when flavours is ran with lightweight flag
# light = true

[[items]]
file = "$XDG_CONFIG_HOME/rofi/themes/colors.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[items]]
file = "$XDG_CONFIG_HOME/polybar/colors.ini"
template = "polybar"
subtemplate = "default"
rewrite = true
hook = "$XDG_CONFIG_HOME/polybar/launch.sh"

[[items]]
file = "$XDG_CONFIG_HOME/kitty/colors.conf"
template = "kitty"
subtemplate = "default-256"
rewrite = true
hook = "pkill -USR1 kitty"
